from django.urls import path

from vaccineapp import views, admin_views, user_views, nurse_views

urlpatterns = [
    path('', views.index, name='index.html'),
    path('AdminPanel', views.AdminPanel, name='AdminPanel'),
    path('NursePanel', views.NursePanel, name='NursePanel'),
    path('UserPanel', views.UserPanel, name='UserPanel'),
    path('nurse_view', admin_views.nurse_view, name='nurse_view'),
    path('user_view', admin_views.user_view, name='user_view'),
    path('hospital_view', admin_views.hospital_view, name='hospital_view'),
    path('vaccine_view', admin_views.vaccine_view, name='vaccine_view'),
    path('complaint_view', admin_views.complaint_view, name='complaint_view'),
    path('appointment_view', admin_views.appointment_view, name='appointment_view'),
    path('report_view', admin_views.report_view, name='report_view'),
    path('hospital_add', admin_views.hospital_add, name='hospital_add'),
    path('vaccine_add', admin_views.vaccine_add, name='vaccine_add'),
    path('report_add', admin_views.report_add, name='report_add'),
    path('nurse_delete/<int:id>/', admin_views.nurse_delete, name='nurse_delete'),
    path('user_delete/<int:id>/', admin_views.user_delete, name='user_delete'),
    path('hospital_delete/<int:id>/', admin_views.hospital_delete, name='hospital_delete'),
    path('vaccine_delete/<int:id>/', admin_views.vaccine_delete, name='vaccine_delete'),
    path('appointment_delete/<int:id>/', admin_views.appointment_delete, name='appointment_delete'),
    path('report_delete/<int:id>/', admin_views.report_delete, name='report_delete'),
    path('complaint_delete/<int:id>/', admin_views.complaint_delete, name='complaint_delete'),
    path('hospital_update/<int:id>/', admin_views.hospital_update, name='hospital_update'),
    path('vaccine_update/<int:id>/', admin_views.vaccine_update, name='vaccine_update'),
    path('complaint_reply/<int:id>/', admin_views.complaint_reply, name='complaint_reply'),
    path('user_view_nurse', nurse_views.user_view, name='user_view_nurse'),
    path('hospital_view_nurse', nurse_views.hospital_view, name='hospital_view_nurse'),
    path('vaccine_view_nurse', nurse_views.vaccine_view, name='vaccine_view_nurse'),
    path('complaint_view_nurse', nurse_views.complaint_view, name='complaint_view_nurse'),
    path('vaccinationSchedule_view_nurse', nurse_views.vaccinationSchedule_view, name='vaccinationSchedule_view_nurse'),
    path('vaccinationSchedule_add_nurse', nurse_views.vaccinationschedule_add, name='vaccinationSchedule_add_nurse'),
    path('complaint_add_nurse', nurse_views.complaint_add, name='complaint_add_nurse'),
    path('vaccinationSchedule_delete/<int:id>/', nurse_views.vaccinationSchedule_delete,
         name='vaccinationSchedule_delete'),
    path('vaccinationSchedule_update/<int:id>/', nurse_views.vaccinationSchedule_update,
         name='vaccinationSchedule_update'),
    path('appointment_status', nurse_views.appointment_status, name='appointment_status'),
    path('mark_vaccinated/<int:id>/', nurse_views.mark_vaccinated, name='mark_vaccinated'),
    path('unmark_vaccinated/<int:id>/', nurse_views.unmark_vaccinated, name='unmark_vaccinated'),
    path('profile_view', user_views.profile_view, name='profile_view'),
    path('vaccinationSchedule_view_user', user_views.vaccinationSchedule_view, name='vaccinationSchedule_view_user'),
    path('appointment_view_status', user_views.appointment_view, name='appointment_view_status'),
    path('nurse_registration', views.Nurse_register, name='nurse_registration'),
    path('user_registration', views.User_register, name='user_registration'),
    path('book_appointment/<int:id>/', user_views.book_appointment, name='book_appointment'),
    path('login_view', views.login_view, name='login_view'),
    path('profile_update/<int:id>/', user_views.profile_update, name='profile_update'),
    path('complaint_register', user_views.register_complaint, name='complaint_register'),
    path('complaint_reply', user_views.complaint_view, name='complaint_reply'),
    path('report_card_view', user_views.report_card_view, name='report_card_view'),
    path('confirm_appointment/<int:id>/', admin_views.confirm_appointment, name='confirm_appointment'),
    path('reject_appointment/<int:id>/', admin_views.reject_appointment, name='reject_appointment'),
    path('logout',views.logout_view,name='logout')

]
