# Generated by Django 4.0.1 on 2022-02-17 16:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_nurse', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Contact_No', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vaccine_Name', models.CharField(max_length=200)),
                ('Vaccine_Type', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Approval_Status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Address', models.TextField(max_length=200)),
                ('Child_Name', models.CharField(max_length=200)),
                ('Child_Age', models.IntegerField()),
                ('Child_Gender', models.CharField(max_length=100)),
                ('Recent_Vaccination', models.TextField(null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='vaccineapp.user')),
                ('Vaccine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vaccine', to='vaccineapp.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=200)),
                ('Contact_No', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vaccineapp.hospital')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('Complaint', models.TextField()),
                ('Date', models.DateField()),
                ('Reply', models.TextField(blank=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=0)),
                ('Vaccinated', models.BooleanField(default=False)),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccineapp.vaccinationschedule')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='vaccineapp.user')),
                ('Vaccine_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vaccineapp.vaccine')),
            ],
        ),
    ]
