# Generated by Django 4.0.1 on 2022-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0002_alter_hospital_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(max_length=200),
        ),
    ]
